server/config.ts, server/utils/nunjucksSetup.ts, server/views/partials/caseloadBar.njk
…and point out that `production` config & template parameter is true in dev, preprod _and_ prod
=> Fix caseload bar to not show warning tag in `prod`

assets/scss/application.scss, assets/scss/components/_sortable-table.scss
… which can be used with the [GOV.UK Table component](https://design-system.service.gov.uk/components/table/) to style it _similarly_ to the [MoJ Sortable table component](https://design-patterns.service.justice.gov.uk/components/sortable-table/).
```html
<div class="app-sortable-table-container">
{{ govukTable({
…
classes: "app-sortable-table"
}) }}
</div>
```
NB: the MoJ Sortable table component is only able to sort one page’s worth of rows _in the browser_, it cannot work with data that is sorted on the back-end. The above code makes a regular GOV.UK Table _look_ like this component.
=> NON-104: Copy sortable table styles from incentives-ui

server/middleware/breadcrumbs.ts, server/routes/add.test.ts, server/routes/add.ts, server/routes/prisonerSearch.test.ts, server/routes/prisonerSearch.ts, server/routes/view.test.ts, server/routes/view.ts, server/sanitisedError.ts, server/utils/nunjucksSetup.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/pages/add.njk
All "add" and "view" pages/routes have the concept of a key prisoner. This person’s details need to be loaded when the routes are being processed. If the person is not found: 404.
=> NON-104: Load the key prisoner’s details

integration_tests/mockApis/nonAssociationsApi.ts, server/data/nonAssociationsApi.ts, server/data/offenderSearch.ts, server/data/testData/nonAssociationsApi.ts, server/data/testData/offenderSearch.ts, server/forms/add.test.ts, server/forms/add.ts, server/routes/add.ts
Currently supports listing, adding, updating and closing non-associations.
Depends on [api#42](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/42)
=> NON-104 & NON-105: Update non-associations api client to match latest (WIP) data model

server/routes/update.test.ts, server/routes/update.ts
Once non-associations are closed can't be edited directly by the user.
Route returns 404 to indicate the page to edit a closed non-association doesn't "exist".
=> NON-145: Prevent editing of closed non-associations

integration_tests/pages/nonAssociations/closePrisonerDetails.ts, server/data/nonAssociationsApi.ts, server/forms/close.test.ts, server/forms/close.ts, server/routes/close.test.ts, server/routes/close.ts, server/views/pages/close.njk
Depends on [api#66](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/66)
=> Rename close request fields to match api changes

integration_tests/e2e/list.cy.ts, integration_tests/mockApis/offenderSearchApi.ts, server/data/offenderSearch.ts, server/data/testData/offenderSearch.ts, server/routes/add.test.ts, server/routes/add.ts, server/routes/list.test.ts, server/routes/list.ts, server/routes/prisonerSearch.test.ts, server/routes/prisonerSearch.ts, server/routes/view.test.ts, server/utils/nunjucksSetup.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/pages/list.njk, server/views/pages/view.njk, server/views/partials/keyPrisonerDetails.njk
This is mostly about prisoners’ location display and the "list" page still only shows one table of non-associations. I.e. the list is still not split by establishment.
=> NON-193: List non-associations page

server/data/nonAssociationsApi.test.ts, server/data/nonAssociationsApi.ts, server/routes/list.ts, server/views/pages/list.njk, server/views/partials/nonAssociationGroup.njk
Nunjucks macros do not inherit variables visible in the template so it's easy to forget to pass them in. Here, `dpsUrl` was missing and now that so many parameters would need to be passed in it seems better to use a plain include.
=> NON-193: Fix prisoner profile links

assets/js/application.js, integration_tests/e2e/add.cy.ts, integration_tests/e2e/close.cy.ts, integration_tests/e2e/update.cy.ts, server/views/pages/addConfirmation.njk, server/views/pages/closeConfirmation.njk, server/views/pages/updateConfirmation.njk
The Add/Update/Close confirmation pages have a link that takes the user
back to the "key" prisoner's non-associations page.
Clicking on these now publishes a custom GA event (with name `non_associations_event`).
The `category` field in the event can be used to filter/discriminate between
pages in a GA report.
In this specific case `action`/`label` fields are blank but if we'll ever add more custom GA events
it may make sense for these future events to also potentially set `action` and/or `label` (
by setting the `data-ga-action` and/or `data-ga-label` attributes).
For the simple case of clicks these are not necessary.
NOTE: The `active_case_load` property is also sent alongside in the published events, even if this is not passed explicitly on send.
=> NON-209: Track clicks on confirmation pages

README.md
The README mentioned the non-associations-api but it also said this was a facade to NOMIS which was wrong (UI never used legacy endpoint IIRC) and also not important/an implementation detail anyway:
Removed this sentence:
> which currently is a facade to information held in NOMIS but will
> become the single source of truth in future.
=> NON-265: Removed mention of NOMIS in README

integration_tests/e2e/add.cy.ts, server/data/constants.ts, server/middleware/userPermissions.test.ts, server/middleware/userPermissions.ts, server/routes/prisonerSearch.ts, server/routes/testutils/appSetup.ts, server/views/pages/prisonerSearch.njk
…to allow users with “global search” to add/update/close non-associations between a prisoner in their caseloads and one in a prison outside their caseloads.
NB: The first commit doesn't change the rules, but simply adds tests to cover every combo of prisoner locations.
When checking roles and caseloads, the new rules are…
- forbid non-prison users from viewing or modifying any non-associations
- allow prison users to view all non-associations
- allow prison users to only modify non-associations in their caseloads
- allow prison users with global search to modify non-associations in transfer or when at least one is in their caseloads
- allow prison users with inactive bookings to modify non-associations in their caseloads or outside
- allow prison users with global search and inactive …
=> NON-281: Relax caseload restrictions for modifying non-associations

server/data/testData/offenderSearch.ts, server/middleware/userPermissions.test.ts, server/middleware/userPermissions.ts
This allegedly indicates they have no booking.
Related: [api#152](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/152)
=> NON-287: Disallow adding a non-associations to prisoners with NO location

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml
Enable 'scheduled downtime' feature of generic-service helm chart: https://github.com/ministryofjustice/hmpps-helm-charts/tree/main/charts/generic-service#scheduled-downtime
> To enable this feature, you first need to add a `scheduled-downtime-serviceaccount`
> Service Account to your namespace, with permissions to scale your deployment.
The required kubernetes `ServiceAccount` is already there:
- `dev`: https://github.com/ministryofjustice/cloud-platform-environments/blob/ed74f5b567c5e8e2f2aab90a92263f23021ca106/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-dev/resources/scheduled-downtime.tf
- `preprod`: https://github.com/ministryofjustice/cloud-platform-environments/blob/ed74f5b567c5e8e2f2aab90a92263f23021ca106/namespaces/live.cloud-platform.service.justi …
=> NON-303: Stop non-prod instances during non-working hours

.circleci/config.yml, helm_deploy/values-preprod.yaml
…keeping `prod` unchanged for now to test the set actually applied to the ingress.
Expectation is that 5 SSCL ranges will disappear, but they are very likely to not be needed.
=> Move `preprod` to use shared IP address allow lists

server/data/prisonApi.test.ts, server/data/prisonApi.ts, server/data/restClient.ts
`prison-api` now (sensibly!) returns 403 instead of 404 if token is unauthorised. We should swallow the error and:
• display default image when user is not authorised to view a prisoner’s photo
• display username when user is not authorised to look up a staff member’s name
=> NON-318: Handle `prison-api` 403

server/middleware/userPermissions.test.ts, server/middleware/userPermissions.ts, server/routes/add.test.ts, server/routes/close.test.ts, server/routes/prisonerSearch.test.ts, server/routes/prisonerSearch.ts, server/routes/update.test.ts, server/routes/view.test.ts, server/views/pages/prisonerSearch.njk
… so that if a prisoner is in your caseloads, it doesn't matter if the other is being transferred or has been released – global search and inactive bookings roles aren't required to add/update/close non-associations. Which means that the prisoner search page no longer needs the variation that searches only in the current caseload.
=> NON-337: Relax role-based restrictions

server/views/pages/list.njk, server/views/pages/view.njk, server/views/partials/helpWithRoles.njk
Macros do not inherit global context so email variable needs to be passed in
=> NON-340: Fix display of email address in help-with-roles message

.eslintrc.json, helm_deploy/hmpps-non-associations/values.yaml, package-lock.json, package.json, server/config.ts, server/data/hmppsAuditClient.test.ts, server/data/hmppsAuditClient.ts, server/services/auditService.test.ts, server/services/auditService.ts
Copied from [upstream template](https://github.com/ministryofjustice/hmpps-template-typescript/pull/327) but the audit client is _not_ provided to the app’s “services”
=> Add (disabled) audit client (hmpps-template-typescript#327)

package-lock.json, package.json, server/middleware/setUpWebSecurity.ts
[`v3.7.2`] doesn't use inline style so custom CSP to make it work is no longer necessary.
[`v3.7.2`]: https://github.com/ministryofjustice/hmpps-digital-prison-reporting-frontend/issues/82#issuecomment-2040040883
=> NON-347: Updated DPR and removed now unnecessary CSP config

.circleci/config.yml
Ref [api#294](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/294)
=> NON-318: Use latest LTS java for Veracode scanning

server/utils/nunjucksSetup.ts
The app runs from within the `/dist` folder into which assets are built along with the *manifest* file. This manifest file is used from within nunjucks templates to map local paths to versioned assets.
However, tests run from the actual sources and cannot find the manifest file, leading to a wall of inconsequential error messages.
For now it’s easiest to silence this error in test mode. `jest` tests don’t actually even try to load any assets; there is no server running.
Once the template project decides on a better workaround, we can cherry-pick it and remove this solution.
=> NON-318: Silence asset manifest file error during tests

.circleci/config.yml, integration_tests/tsconfig.json
• `eslint` already ran in CircleCI build job but for some reason `tsc` did not
• integration tests now compile to a more-modern version of javascript
=> NON-318: Run type-checking in CircleCI

helm_deploy/hmpps-non-associations/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Send alerts to our Slack dev channel (`#non-associations-dev`) instead of sending them to `#dps_alers`/`#dps_alerts_non_prod`.
=> NON-318: Send alerts to dev channel

helm_deploy/hmpps-non-associations/values.yaml
…the k8s secret itself is created by terraform from a shared DPS secret in a AWS systems manager parameter
Ref: [hmpps-template-typescript#485](https://github.com/ministryofjustice/hmpps-template-typescript/pull/485)
=> NON-318: Get Azure Application Insights settings from kubernetes secret directly

helm_deploy/hmpps-non-associations/values.yaml, helm_deploy/values-prod.yaml
Use UTC and ensure API starts before UI/first retry-dlq run and stops after UI and last retry-dlq run.
- [6:49am API starts](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/479/files#diff-111793a49467782683fd0ba65ed3cd6b413e2d247949b363e035a05a00002321R16-R17)
- 7:00am UI starts
- [7:00am retry-dlq run every 10 minutes](https://github.com/ministryofjustice/hmpps-helm-charts/blob/f210af4475dd27689621b491a63d69bbe683de0e/charts/generic-service/values.yaml#L256)
- ...
- 9:50pm retry-dlq last run for the day
- 9:50pm UI stops
- 9:58pm API stops
Sibling of similar [API PR](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/479).
=> IR-1136: Tweaked start/stop schedules

package-lock.json
Bumped to version 0.2.5 (<= 0.2.3 are affected)
https://github.com/advisories/GHSA-52f5-9888-hmc6
=> Security fix for `tmp`: GHSA-52f5-9888-hmc6
