server/utils/azureAppInsights.ts, server/utils/azureAppinsights.test.ts
Copied from https://github.com/ministryofjustice/hmpps-incentives-ui and https://github.com/ministryofjustice/hmpps-book-secure-move-frontend
=> NON-36: Report users’ active case loads to Azure Application Insights

assets/.eslintrc.json, assets/js/application.js, feature.env, helm_deploy/hmpps-non-associations/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, integration_tests/e2e/index.cy.ts, integration_tests/index.d.ts, integration_tests/pages/page.ts, integration_tests/support/commands.ts, integration_tests/support/googleAnalyticsTracker.ts, server/config.ts, server/middleware/setUpWebSecurity.ts, server/utils/nunjucksSetup.ts, server/views/partials/layout.njk
tested locally, page view events are reported to GA, but will need to see in proper hosted environment to ensure that cross-site policies correctly allow tracking
=> NON-35: Track events with Google Analytics

server/utils/format.test.ts, server/utils/format.ts, server/utils/nunjucksSetup.ts
Formatting dates, numbers and possessive forms of names will be needed throughout the app.
The first two are copied directly from incentives-ui
=> NON-108: Add formatting utils

server/app.ts, server/routes/index.ts, server/routes/testutils/appSetup.ts, server/services/index.ts, server/services/routeUrls.ts, server/utils/nunjucksSetup.ts, server/views/pages/view.njk
…so that there’s less repetition of very similar looking strings which would be error-prone
=> NON-104: Make a service that generates urls for routes/views/pages

server/utils/nunjucksSetup.ts
…which will be needed to display, for example, prisoners’ names
=> NON-104: Register title-case util as a nunjucks filter

server/utils/pagination.test.ts, server/utils/pagination.ts
… which can be used with the [GOV.UK Pagination component](https://design-system.service.gov.uk/components/pagination/) to generate the appropriate page ranges and links.
=> NON-104: Copy pagination utility from incentives-ui

assets/scss/application.scss, assets/scss/components/_field-and-button-group.scss, assets/scss/components/_pagination.scss, assets/scss/components/prisoner-photo.scss, server/data/offenderSearch.ts, server/data/testData/offenderSearch.ts, server/forms/prisonerSearchForm.test.ts, server/forms/prisonerSearchForm.ts, server/routes/add.test.ts, server/routes/prisonerSearch.test.ts, server/routes/prisonerSearch.ts, server/routes/testutils/appSetup.ts, server/routes/view.test.ts, server/views/pages/prisonerSearch.njk, server/views/partials/formErrorSummary.njk
Allows searching for a name or prisoner number using offender search, with appropriate error messages when necessary. Sorting has not been enabled yet.
=> NON-104 & NON-105: Enable searching for a second prisoner search to make a non-association

assets/scss/components/_sortable-table.scss, server/routes/prisonerSearch.test.ts, server/views/pages/prisonerSearch.njk
• Change prisoner search heading when results are shown
• Remove experimental sortable table arrow colours
=> NON-104 & NON-105: Fix prisoner search appearance

server/views/pages/addConfirmation.njk, server/views/pages/closeConfirmation.njk, server/views/pages/updateConfirmation.njk
These templates aren't yet used anywhere, but can probably be considered finished
=> NON-106: Lay out confirmation page templates

server/forms/add.test.ts, server/forms/add.ts, server/routes/add.test.ts, server/routes/add.ts, server/routes/forms/get.test.ts, server/routes/forms/get.ts, server/routes/forms/post.test.ts, server/routes/forms/post.ts, server/utils/checkedItems.test.ts, server/utils/checkedItems.ts, server/utils/nunjucksSetup.ts, server/views/pages/add.njk, server/views/pages/prisonerSearch.njk
…which is laid out as in the designs and validates the form, but is non-functional: i.e. the non-association is _NOT_ persisted.
=> NON-106: Create page for adding non-association details

assets/scss/page/_view.scss, integration_tests/mockApis/nonAssociationsApi.ts, server/data/nonAssociationsApi.test.ts, server/data/nonAssociationsApi.ts, server/data/testData/nonAssociationsApi.ts, server/data/testData/prisonApi.ts, server/forms/add.test.ts, server/forms/close.test.ts, server/forms/close.ts, server/forms/view.test.ts, server/forms/view.ts, server/routes/close.test.ts, server/routes/close.ts, server/routes/index.ts, server/routes/prisonerSearch.test.ts, server/routes/update.test.ts, server/routes/update.ts, server/routes/view.test.ts, server/routes/view.ts, server/services/routeUrls.ts, server/views/pages/close.njk, server/views/pages/closeConfirmation.njk, server/views/pages/view.njk
Depends on [api#51](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/51)
=> NON-148, NON-149, NON-150 & NON-151: Close non-associations

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Reverts ministryofjustice/hmpps-non-associations#114
Taking out for now until resolve some MOD issues
=> Revert "NON-220 Add Mod security to UI"

server/routes/list.test.ts, server/routes/list.ts
=> NON-193: Disallow sorting "outside" table by location

server/views/pages/list.njk, server/views/pages/view.njk, server/views/partials/keyPrisonerDetails.njk, server/views/partials/keyPrisonerDetailsForList.njk, server/views/partials/keyPrisonerDetailsForView.njk
Same problem as in #120, but just a different component! There's a bit too much global state to compartmentalise templates into macros :(
=> NON-193: Fix prisoner profile links

server/routes/add.ts, server/routes/update.ts
=> Fix system token sharing between form constructors and request handlers

assets/scss/application.scss, assets/scss/components/_pagination.scss, server/routes/close.test.ts, server/routes/prisonerSearch.test.ts, server/routes/prisonerSearch.ts, server/routes/update.test.ts, server/routes/update.ts, server/utils/pagination.test.ts, server/utils/pagination.ts, server/views/pages/add.njk, server/views/pages/close.njk, server/views/pages/prisonerSearch.njk, server/views/pages/update.njk, server/views/partials/nonAssociationForm.njk
• use a link where simple navigation takes place instead of a button
• use legacy MoJ pagination component for prisoner search
=> NON-211: Design tweaks

.circleci/config.yml, renovate.json
Fixes something omitted from #143
=> Use latest HMPPS CircleCI orb

integration_tests/mockApis/nonAssociationsApi.ts, server/data/nonAssociationsApi.ts, server/data/testData/nonAssociationsApi.ts
At this point the API format and structure is relatively stable (although as everything in life, there is always room for improvement and changes)
=> NON-265: Removed TODO comments about API being WIP

server/data/nonAssociationsApi.ts, server/data/offenderSearch.ts, server/data/prisonApi.ts, server/data/restClient.test.ts, server/data/restClient.ts
=> Improve REST client by allowing query parameters to be passed for all methods

renovate.json
Reverts ministryofjustice/hmpps-non-associations#218
=> Revert "Auto-merge renovate’s non-major npm updates"

assets/scss/application.scss, assets/scss/components/_links.scss, assets/scss/components/_sortable-table.scss, server/views/pages/view.njk, server/views/partials/breadcrumbs.njk, server/views/partials/feedbackBanner.njk, server/views/partials/miniProfileHeader.njk, server/views/partials/miniProfileHeaderForList.njk, server/views/partials/nonAssociationGroup.njk
…by:
• removing buttons and navigation which distract from the content
• turning links into plain text – black and without underline
=> NON-318: Improve print layout

Dockerfile, package.json
=> Move to Debian 12 / bookworm

assets/scss/application.scss, package-lock.json, package.json, server/middleware/setUpStaticResources.ts, server/routes/index.ts, server/utils/nunjucksSetup.ts, server/views/partials/layout.njk, server/views/partials/reportsLayout.njk
UI counterpart to [API changes](https://github.com/ministryofjustice/hmpps-non-associations-api/pull/240)
=> NON-347: DPR Spike - added `/reports` endpoint

server/middleware/setUpWebSecurity.ts
[I've also raised an issue with DPR library here](https://github.com/ministryofjustice/hmpps-digital-prison-reporting-frontend/issues/82) in case they have ideas on a better way of dealing with this.
=> NON-347: Tweak CSP policy to avoid errors in DPR/reports page

.circleci/config.yml, package-lock.json, package.json
=> NON-318: Complete upgrade to Node 20.12

helm_deploy/values-prod.yaml
Ref: [prison-api#2156](https://github.com/ministryofjustice/prison-api/pull/2156)
=> NON-318: Migrate to `prison-api` in Cloud Platform

package-lock.json, package.json
=> NON-318: Update dependencies
